language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
install:
  - "pip install -r requirements.txt"
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install bernhard protobuf dnspython; fi
  - if [[ $TRAVIS_PYTHON_VERSION != '2.7' ]]; then pip install dnspython3; fi
script: "./run_tests.py"
